# SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS
BORT_SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS := $(BORT_PATH)/sepolicy/common $(BORT_PATH)/sepolicy/private
ifeq (,$(findstring $(BORT_SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS),$(SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS)))
  SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS += $(BORT_SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS)
endif
BORT_BOARD_PLAT_PRIVATE_VERSION_SEPOLICY_DIR := $(BORT_PATH)/sepolicy/private-$(PLATFORM_SDK_VERSION)
ifneq (,$(wildcard $(BORT_BOARD_PLAT_PRIVATE_VERSION_SEPOLICY_DIR)))
  ifeq (,$(findstring $(BORT_BOARD_PLAT_PRIVATE_VERSION_SEPOLICY_DIR),$(SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS)))
    SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS += $(BORT_BOARD_PLAT_PRIVATE_VERSION_SEPOLICY_DIR)
  endif
endif

# SYSTEM_EXT_PUBLIC_SEPOLICY_DIRS
BORT_SYSTEM_EXT_PUBLIC_SEPOLICY_DIRS := $(BORT_PATH)/sepolicy/public
ifeq (,$(findstring $(BORT_SYSTEM_EXT_PUBLIC_SEPOLICY_DIRS),$(SYSTEM_EXT_PUBLIC_SEPOLICY_DIRS)))
  SYSTEM_EXT_PUBLIC_SEPOLICY_DIRS += $(BORT_SYSTEM_EXT_PUBLIC_SEPOLICY_DIRS)
endif
BORT_BOARD_PLAT_PUBLIC_VERSION_SEPOLICY_DIR := $(BORT_PATH)/sepolicy/public-$(PLATFORM_SDK_VERSION)
ifneq (,$(wildcard $(BORT_BOARD_PLAT_PUBLIC_VERSION_SEPOLICY_DIR)))
  ifeq (,$(findstring $(BORT_BOARD_PLAT_PUBLIC_VERSION_SEPOLICY_DIR),$(SYSTEM_EXT_PUBLIC_SEPOLICY_DIRS)))
    SYSTEM_EXT_PUBLIC_SEPOLICY_DIRS += $(BORT_BOARD_PLAT_PUBLIC_VERSION_SEPOLICY_DIR)
  endif
endif

$(warning BOARD_SEPOLICY_DIRS - $(BOARD_SEPOLICY_DIRS))
$(warning BOARD_SEPOLICY_M4DEFS - $(BORT_BOARD_SEPOLICY_M4DEF))
$(warning SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS - $(SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS))
$(warning SYSTEM_EXT_PUBLIC_SEPOLICY_DIRS - $(SYSTEM_EXT_PUBLIC_SEPOLICY_DIRS))
